# basic Travis script to run ANTLR CI tests for OpenQASM
language: python
python: 3.7
install: pip install -r requirements.txt
before_script:
  - sudo curl https://www.antlr.org/download/antlr-4.9.2-complete.jar -o /usr/local/lib/antlr-4.9.2-complete.jar
  - export CLASSPATH=".:/usr/local/lib/antlr-4.9.2-complete.jar:$CLASSPATH"
script:
  - alias antlr4="java -jar /usr/local/lib/antlr-4.9.2-complete.jar"
  - antlr4 -Dlanguage=Python3 source/grammar/qasm3.g4
  - pytest
